spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

riot:
  api:
    key: "RGAPI-aaf11af5-dc2a-4ef5-b881-b67d403f057b"
    account-url: "https://asia.api.riotgames.com/riot/account/v1/accounts/by-riot-id/{gameName}/{tagLine}?api_key={apiKey}"
    matches-url: "https://asia.api.riotgames.com/lol/match/v5/matches/by-puuid/{puuid}/ids?type=ranked&start=0&count=20&api_key={apiKey}"
    match-url: "https://asia.api.riotgames.com/lol/match/v5/matches/{matchId}?api_key={apiKey}"
    mastery-url: "https://kr.api.riotgames.com/lol/champion-mastery/v4/champion-masteries/by-puuid/{puuid}?api_key={apiKey}"
